language: node_js
node_js:
  # - '14'
  - '12'
  # - '10'
os:
  # - linux
  - windows
  # - osx
before_install:
  # - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install mozjpeg; fi
  - | 
      case $TRAVIS_OS_NAME in
      windows)
      choco install -y nasm
      git clone https://github.com/madler/zlib.git /tmp/zlib
      cd /tmp/zlib
      # export PATH=/c/ProgramData/chocolatey/bin:$PATH
      export MAKE=mingw32-make
      cmake -G"MSYS Makefiles" -DCMAKE_MAKE_PROGRAM="/c/ProgramData/chocolatey/bin/mingw32-make.exe" -DCMAKE_C_COMPILER='/c/ProgramData/chocolatey/bin/x86_64-w64-mingw32-gcc.exe'  -DCMAKE_AR="/c/ProgramData/chocolatey/bin/ar.exe" .
      /c/ProgramData/chocolatey/bin/mingw32-make.exe
      /c/ProgramData/chocolatey/bin/mingw32-make.exe test
      cd ..
      git clone https://github.com/glennrp/libpng /tmp/libpng
      cd /tmp/libpng
      cmake -G"MSYS Makefiles" -DCMAKE_MAKE_PROGRAM="/c/ProgramData/chocolatey/bin/mingw32-make.exe" -DCMAKE_C_COMPILER='/c/ProgramData/chocolatey/bin/x86_64-w64-mingw32-gcc.exe'  -DCMAKE_AR="/c/ProgramData/chocolatey/bin/ar.exe" -DZLIB_LIBRARY="/tmp/zlib/libzlib.dll.a" -DZLIB_INCLUDE_DIR="/tmp/zlib" .
      /c/ProgramData/chocolatey/bin/mingw32-make.exe
      cp scripts/pnglibconf.h.prebuilt pnglibconf.h
      cp scripts/makefile.msys makefile
      /c/ProgramData/chocolatey/bin/mingw32-make.exe test
      cd ..
      git clone https://github.com/mozilla/mozjpeg.git /tmp/mozjpeg
      cd /tmp/mozjpeg
      cmake -G"MSYS Makefiles" -DCMAKE_MAKE_PROGRAM="/c/ProgramData/chocolatey/bin/mingw32-make.exe" -DCMAKE_C_COMPILER='/c/ProgramData/chocolatey/bin/x86_64-w64-mingw32-gcc.exe' -DZLIB_LIBRARY="/tmp/zlib/libzlib.dll.a" -DZLIB_INCLUDE_DIR="/tmp/zlib" -DPNG_LIBRARY="/tmp/libpng/libpng16.a" -DPNG_PNG_INCLUDE_DIR="/tmp/libpng" -DCMAKE_AR="/c/ProgramData/chocolatey/bin/ar.exe" .
      CC='/c/ProgramData/chocolatey/bin/i686-w64-mingw32-gcc.exe' /c/ProgramData/chocolatey/bin/mingw32-make.exe
      git clone https://github.com/danielgtaylor/jpeg-archive.git /tmp/jpeg-archive
      cd /tmp/jpeg-archive
      CC='/c/ProgramData/chocolatey/bin/i686-w64-mingw32-gcc.exe' /c/ProgramData/chocolatey/bin/mingw32-make.exe
      ;;
      osx)
      brew install mozjpeg
      ;;
      esac
script:
  - echo "Completed!!!"